name: CustomCore
version: 1.0.0
main: RTG\Core\MyCore
api: 2.1.0
author: IG
commands:
    gms:
        permission: server.command.gamemode
permissions:
    server.command.gamemode:
        default: op